---
- name: install the latest Composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer warn=False
  args:
    creates: /usr/local/bin/composer

- name: install git
  package: name=git state=latest

- name: clone Drush repository
  git:
    repo: https://github.com/drush-ops/drush.git
    version: "9.3.0"
    dest: /opt/drush

- name: install Drush dependencies with Composer
  shell: composer install
  args:
    chdir: "/opt/drush"

- name: create the Drush executable link
  file:
    src: /opt/drush/drush
    dest: /usr/local/bin/drush
    state: link

- name: install mysql client
  package: name=mysql-client state=present

- name: create the Drupal install directory
  file:
    path: "{{ drupal_site_path }}"
    state: directory

- name: clone Drupal repository
  git:
    repo: http://git.drupal.org/project/drupal.git
    version: "{{ drupal_version }}"
    dest: "{{ drupal_site_path }}"

- name: install Drupal dependencies with Composer
  shell: composer install
  args:
    chdir: "{{ drupal_site_path }}"
    creates: "{{ drupal_site_path }}/vendor/autoload.php"

- name: install Drupal
  shell: drush si -y --site-name="{{ drupal_site_name }}" --account-name={{ drupal_admin_username }} --account-pass="{{ drupal_admin_pass }}" --db-url=mysql://{{ drupal_db_user }}:{{ drupal_db_pass }}@127.0.0.1/{{ drupal_db_name }}
  args:
    chdir: "{{ drupal_site_path }}"

- name: set proper ownership
  file:
    path: "{{ drupal_site_path }}"
    owner: www-data
    group: www-data
    recurse: yes

- name: set permissions on the settings file
  file:
    path: "{{ drupal_site_path }}/sites/default/settings.php"
    mode: 0744

- name: set permissions on files direcotry
  file:
    path: "{{ drupal_site_path }}/sites/default/files"
    mode: 0777
    state: directory
    recurse: yes
